### ISSUE TITLE
Is this the codebase for the WACV 2021 paper?

### ISSUE THREAD

**Issue by xinmiaolin** [shinkyo0513/Video-Visual-Explanations#1]
Hi,

Thanks a lot for this fantastic code repo.

Could you confirm whether this code repo can reproduce the results in the paper "Towards Visually Explaining Video Understanding Networks with Perturbation"?

Thank you very much!

**Comment by shinkyo0513** [comment]
Hi,

I have updated the repo and it now contains the methods investigated in the WACV 2021 paper.

Thanks!
