### ISSUE TITLE
UCF101 kernel size issue for STEP algorithm

### ISSUE THREAD

**Issue by xinmiaolin** [shinkyo0513/Video-Visual-Explanations#3]
Hi,

I added UCF-101 to the codebase and tested STEP, 2D_EP, 3D_EP, the latter two run fine on the whole UCF-101 validation dataset, while STEP fails for some videos, with the error shown on the picture

![Screenshot from 2021-01-29 21-08-45](https://user-images.githubusercontent.com/43487018/106344035-83b0d800-6276-11eb-9733-8f868209d1e4.png)

If you could help with this, I would really appreciate it.

Thank you!

**Comment by shinkyo0513** [comment]
Hi, if you could paste the codes around line 382 of your perturbation.py, it would be helpful. I am not sure it is consistent with my original code. 

By the way, I always tested by PRESERVE_VARIANT or DELETE_VARIANT. So maybe some error would happen in tensor shape if you test the DUAL_VARIANT.
